### PR TITLE
add cocoapods support

### PR DESCRIPTION
**Pull request by ozby**
pod install support

### CODE REVIEW

**Comment by DajePepo** [comment]
It seems there is not any pod with the name "react-native-piwik" indeed pod install returns an error.

**Comment by forteil** [comment]
Hey!
It seems that now the pod for Matomo exists, please be so kind as to update your pull request with the new version of Matomo pod.

**Comment by partiellkorrekt** [comment]
How would one update this pull request to use the new Natomo pod? I would love to see this PR merged because it is essential for RN 0.60.* compatibility.

**Comment by hugo-marques-m3** [comment]
Are the conflicts the only thing that's preventing this from getting fixed?

**Comment by hugo-marques-m3** [comment]
@ozby did you manage to have this working in the end using pods?

**Comment by ozby** [comment]
hey @hugo-marques-m3 , unfortunately we are not using this pod anymore, i just tried to update it to make it work again after seeing comments here, but it is not in working condition. I am going to look at it when i have more time.

**Comment by hugo-marques-m3** [comment]
Thanks for answering @ozby. Out of curiosity did you stop using Matomo or are you using another library for Matomo?

**Comment by aeirola** [comment]
@hugo-marques-m3 I've been maintaining an alternative library at https://github.com/terveystalo/react-native-matomo-sdk which supports cocoapods. Unfortunately it doesn't yet support all of the tracking features of this library.

**Comment by hugo-marques-m3** [comment]
Hi @aeirola, thanks for replying. I've seen that library and unfortunately we need setUserID for our use-case. I really need to learn Swift.

**Pull request closed without merging**
